# Pengaturan Waktu Daily Reset (WIB)
daily-reset-hour-wib: 6

moon-effect-start: 13000
moon-effect-end: 22500

# =================
# SKILL SETTINGS
# =================

skills:

  blink:
    cooldown: 8
    range: 25
    damage: 6
    speed-tick: 2
    lightning: true
    particle: ELECTRIC_SPARK

  dash:
    cooldown: 6
    dash-back: 1.5
    dash-forward: 3
    damage: 5
    particle: SWEEP_ATTACK

  domain:
    cooldown: 40

    sky-crack-particle: DRAGON_BREATH
    rune-particle: ENCHANTMENT_TABLE

    sword:
      size: 15
      height: 30
      block: NETHERITE_BLOCK

    impact:
      damage: 15
      radius: 8
      shockwave-particle: EXPLOSION_LARGE
      ground-crack-particle: BLOCK_CRACK

# =================
# MESSAGES
# =================

messages:

  blink: "&b⚡ Lightning Blink!"
  dash: "&f⚔ Moon Dash!"
  domain: "&5✦ Divine Sword Domain!"

  skill-cooldown: "&cSkill cooldown %time%s"
