name: GoldenRamadhan
version: 1.0
main: com.ramadhan.GoldenMoon
api-version: '1.21'
commands:
  goldenmoon:
    aliases: [gm]
    description: Menu Daily dan Command Admin.

permissions:
  goldenmoon.admin:
    description: Izin khusus untuk mengambil pedang via command.
    default: op
